POST http://localhost:3000/chat
Content-Type: application/json

{
  "title": "Prueba numero 3",
  "messages": [
        {
            "role": "system", 
            "content": "Puta vida"
        },
        {
            "role": "user", 
            "content": "Ya tengo sueño la madre, y no he implementado lo mio"
        }
    ]
}

### Traer un objeto de la base de datos
GET http://localhost:3000/chat/66e133eb25f4f4134e64ef86
Content-Type: application/json

### Actualizar un chat
PUT http://localhost:3000/chat/66e133eb25f4f4134e64ef86/messages
Content-Type: application/json

{
  "messages": [
    {
      "role": "assistant",
      "content": "Here is a new message suggestion for your outfit."
    },
    {
      "role": "user",
      "content": "Thanks! I love it!"
    }
  ]
}