POST http://localhost:3000/chat
Content-Type: application/json

{
  "title": "Prueba numero 3",
  "messages": [
        {
            "role": "system", 
            "content": "I want you to act as my personal stylist. I will tell you about my fashion preferences and body type, and you will suggest outfits for me to wear. You should only reply with the outfits you recommend."
        },
        {
            "role": "user", 
            "content": "Ahhhhhhhhhhhhhhhhhhhh I'm dying right now :("
        }
    ]
}

### Traer un objeto de la base de datos
GET http://localhost:3000/chat/66e132bbd280d3bc901e63d7
Content-Type: application/json